name: build

on: [push, pull_request]  # Define en qué eventos se activará el flujo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Test with Maven
        run: mvn -B package --file pom.xml
      - name: Run tests
        run: mvn test --file pom.xml
